# Generated by Django 4.1.2 on 2022-10-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rice')),
            ],
        ),
    ]
