# Generated by Django 4.1.2 on 2022-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_picked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Ethnicity', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='picked',
            options={'ordering': ['-date']},
        ),
    ]
