# Generated by Django 4.1.2 on 2022-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dishes_alter_picked_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='Ethnicity',
            new_name='ethnicity',
        ),
    ]
